---
- name: Deploy Inception on Cloud-1
  hosts: inception
  become: yes
  vars:
    target_user: "{{ ansible_user }}"
    data_mount_point: "/home/{{ ansible_user }}/data"
    project_src: "{{ playbook_dir }}/../inception"
    dest_path: "/home/{{ ansible_user }}/inception"
    disk_device_id: "google-inception_data"
  
  roles:
    - common
    - inception
